CREATE DATABASE IF NOT EXISTS fec;

USE fec;

CREATE TABLE IF NOT EXISTS clicktracker (
  id INT AUTO_INCREMENT,
  clicktime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  element TEXT,
  module TEXT,
  PRIMARY KEY(id)
)